### ISSUE TITLE
Bump gedmo/doctrine-extensions version

### ISSUE THREAD

**Issue by tlorens** [antishov/StofDoctrineExtensionsBundle#13]
composer is looking for 2.3.x.  2.4.39 is available and resolves package version conflicts.

**Comment by antishov** [comment]
Hi, @tlorens 
I think about it from the start. 
This dependency is outdated for years. Are we able to upgrade it and be sure that everything works fine?

**Comment by ovgray** [comment]
Composer is looking for "^2.3.4" which means ">=2.3.4 <3.0.0".

**Comment by ErnadoO** [comment]
@adrx true:
> composer show gedmo/doctrine-extensions
> name     : gedmo/doctrine-extensions
> descrip. : Doctrine2 behavioral extensions
> keywords : Blameable, behaviors, doctrine2, extensions, gedmo, loggable, nestedset, sluggable, sortable, timestampable, translatable, tree, uploadable
> versions : * v2.4.39
