### ISSUE TITLE
Rename from "StofDoctrineExtensionsBundle" to "DoctrineExtensionsBundle"

### ISSUE THREAD

**Issue by Coffee2CodeNL** [antishov/StofDoctrineExtensionsBundle#14]
Might be a good idea?

**Comment by antishov** [comment]
Hi, @Coffee2CodeNL 
According to [best practices for reusable bundles](https://symfony.com/doc/current/bundles/best_practices.html#bundle-name) we can't rename it without namespace change. If we do, we will get a lot of breaking changes with previous versions. 
I'm not sure this is a good idea.
Thank you
