### ISSUE TITLE
PHP 7.3 Requirement

### ISSUE THREAD

**Issue by fyrye** [antishov/StofDoctrineExtensionsBundle#16]
Looking through the code, I don't see any specific reasons to require `php >=7.3` as opposed to `^7.2.5` as per Symfony 5.0 currently.

Is there any specific reason that the `symfony/polyfill-php73` is not be able to satisfy the platform requirements and lower the requirements of the package?

**Comment by antishov** [comment]
You're right, there are no reasons to remove PHP 7.2 compatibility. Returned it back in 5469d7e
Thank you
