### ISSUE TITLE
Loggable extends non existing class "Doctrine\ODM\MongoDB\DocumentRepository"

### ISSUE THREAD

**Issue by nkanzari** [antishov/StofDoctrineExtensionsBundle#18]
I'm using Symfony 4.4 and ODM bundle ^4. I'm using loggable extension and it's complaining about not finding class "Doctrine\ODM\MongoDB\DocumentRepository" in "Gedmo\Loggable\Document\Repository\LogEntryRepository". I checked and the class is under "Doctrine\ODM\MongoDB\Repository\DocumentRepository".

**Comment by antishov** [comment]
Hi
It's related to [gedmo/doctrine-extensions](https://github.com/Atlantic18/DoctrineExtensions)
