### ISSUE TITLE
Uploadable is broken in SF5

### ISSUE THREAD

**Issue by ph538834** [antishov/StofDoctrineExtensionsBundle#21]
The uploadable extension uses the deprecated mimetypeguesser class.
this class is gone in sf 5 and the usage no longer possible.
i've forked from the 1.4.2 because master is broken.

**Comment by ph538834** [comment]
https://github.com/antishov/StofDoctrineExtensionsBundle/pull/20

**Comment by antishov** [comment]
Fixed in v1.4.3
