### ISSUE TITLE
Support for gedmo/doctrine-extensions v3.0.0

### ISSUE THREAD

**Issue by igoooor** [antishov/StofDoctrineExtensionsBundle#25]
Hello,

Do you expect to support gedmo/doctrine-extensions v3.0.0 anytime soon?

Thanks and have a great day!

**Comment by antishov** [comment]
Hi, @igoooor 
It seems to be easy to upgrade versions a bit. I think it can be done in one or two weeks.
To be honest, I'm a little suprised that somebody is using my  fork 😃

**Comment by antishov** [comment]
Added support in v1.4.3
Thank you
