### ISSUE TITLE
Compatibility with php8.0

### ISSUE THREAD

**Issue by informatic-revolution** [antishov/StofDoctrineExtensionsBundle#26]
Is there any way we can use the bundle with php8.0 ?

**Comment by antishov** [comment]
Added in v1.4.3
Thank you

**Comment by informatic-revolution** [comment]
@antishov Thank you for the update, unfortunately, it's still not possible to use it with php 8 because of the following dependencies. If I remove the bundle, it works, but then if I try to add it again I get this, I would really appreciate if you can fix it.

Problem 1
    - antishov/doctrine-extensions-bundle[v1.4.1, ..., v1.4.2] require gedmo/doctrine-extensions ^2.3.4 -> satisfiable by gedmo/doctrine-extensions[v2.3.4, ..., v2.4.42].
    - antishov/doctrine-extensions-bundle v1.4.3 requires gedmo/doctrine-extensions ^2.3.4 || ^3.0 -> satisfiable by gedmo/doctrine-extensions[v2.3.4, ..., v2.4.42, v3.0.0].
    - antishov/doctrine-extensions-bundle v1.4.0 requires symfony/framework-bundle ~2.7|~3.2|~4.0 -> found symfony/framework-bundle[v2.7.0, ..., v2.8.52, v3.2.0, ..., v3.4.47, v4.0.0, ..., v4.4.18] but it conflicts with your root composer.json require (5.2.*).
    - gedmo/doctrine-extensions[v2.3.4, ..., v2.3.9] require doctrine/common >=2.2,<2.5-dev -> found doctrine/common[2.2.0, ..., v2.4.3] but the package is fixed to 3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - gedmo/doctrine-extensions[v2.3.10, ..., v2.4.42] require doctrine/common ~2.4 -> found doctrine/common[v2.4.0, ..., 2.13.3] but the package is fixed to 3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - gedmo/doctrine-extensions v3.0.0 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires antishov/doctrine-extensions-bundle ^1.4 -> satisfiable by antishov/doctrine-extensions-bundle[v1.4.0, v1.4.1, v1.4.2, v1.4.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by DanielFrancois** [comment]
Same issue than @informatic-revolution

**Comment by informatic-revolution** [comment]
@antishov any update on this ?

**Comment by antishov** [comment]
Yeah, sorry for that.  I’ll check it in a few days.
It’s a bit strange, because Travis successfully built version with php 8 and Symfony 5.2 on board. 
Could you please attach your composer.json?

**Comment by informatic-revolution** [comment]
Yes sure, here is my compose.json

```
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": ">=7.4",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "antishov/doctrine-extensions-bundle": "^1.4",
        "api-platform/core": "^2.5",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.1",
        "doctrine/doctrine-migrations-bundle": "^3.0",
        "gesdinet/jwt-refresh-token-bundle": "^0.10.0",
        "lexik/jwt-authentication-bundle": "^2.10",
        "nelmio/cors-bundle": "^2.1",
        "ramsey/uuid-doctrine": "^1.6",
        "symfony/asset": "5.2.*",
        "symfony/console": "5.2.*",
        "symfony/dotenv": "5.2.*",
        "symfony/expression-language": "5.2.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "5.2.*",
        "symfony/http-client": "5.2.*",
        "symfony/monolog-bundle": "^3.6",
        "symfony/property-access": "5.2.*",
        "symfony/property-info": "5.2.*",
        "symfony/security-bundle": "5.2.*",
        "symfony/serializer": "5.2.*",
        "symfony/twig-bundle": "5.2.*",
        "symfony/validator": "5.2.*",
        "symfony/yaml": "5.2.*"
    },
    "require-dev": {
        "dama/doctrine-test-bundle": "^6.5",
        "doctrine/doctrine-fixtures-bundle": "^3.4",
        "friendsofphp/php-cs-fixer": "^2.16",
        "phpstan/extension-installer": "^1.0",
        "phpstan/phpstan": "^0.12.50",
        "phpstan/phpstan-doctrine": "^0.12.26",
        "phpstan/phpstan-phpunit": "^0.12.17",
        "phpstan/phpstan-symfony": "^0.12.12",
        "symfony/browser-kit": "^5.2",
        "symfony/css-selector": "^5.2",
        "symfony/debug-bundle": "^5.2",
        "symfony/maker-bundle": "^1.23",
        "symfony/phpunit-bridge": "^5.2",
        "symfony/stopwatch": "^5.2",
        "symfony/var-dumper": "^5.2",
        "symfony/web-profiler-bundle": "^5.2",
        "zenstruck/foundry": "^1.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "classmap": [
            "apps/Kernel.php"
        ],
        "psr-4": {
            "DonaCarmen\\": "src/",
            "DonaCarmen\\Apps\\AdminApi\\": "apps/admin-api/src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "DonaCarmen\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "%ADMIN_APP_DIR%/bin/console cache:clear": "script",
            "%ADMIN_APP_DIR%/bin/console assets:install %ADMIN_APP_DIR%/%PUBLIC_DIR%": "script"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ],
        "php-cs-fixer": [
            "php-cs-fixer fix --diff"
        ],
        "phpstan": [
            "phpstan clear-result-cache",
            "phpstan analyse",
            "phpstan analyse --configuration apps/admin-api/phpstan.neon.dist"
        ],
        "phpunit": [
            "simple-phpunit --testdox"
        ],
        "check-all": [
            "simple-phpunit",
            "php-cs-fixer fix --dry-run",
            "phpstan clear-result-cache",
            "phpstan analyse",
            "phpstan analyse --configuration apps/admin-api/phpstan.neon.dist"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.2.*"
        },
        "admin-app-dir": "apps/admin-api"
    }
}
```

**Comment by antishov** [comment]
I assume that the problem is [here](https://github.com/Atlantic18/DoctrineExtensions/pull/2182)
Travis successfully built the package with `gedmo/doctrine-extensions v2.4.42` wich requires PHP to be greater or equal `5.3.2`, but it can't be installed in your case because you locked `doctrine/common` by the `3.1.0` version

**Comment by informatic-revolution** [comment]
so I guess the solution is to wait that the version 3 of gedmo/doctrine-extensions also accept php 8.0 right ?

**Comment by antishov** [comment]
Yes. Or you can try to use lower version for the `doctrine/common`, see the [log](https://travis-ci.com/github/antishov/StofDoctrineExtensionsBundle/jobs/457561661)

**Comment by informatic-revolution** [comment]
Yes I tried it, unfortunately, I need to lower the version of several dependencies to get it to work.

Thanks a lot for your help, and the good job you are doing here maintaining this bundle. 

I will post here when it works

**Comment by antishov** [comment]
Thanks for your feedback
