### ISSUE TITLE
Composer failures on shared folders

### ISSUE THREAD

**Issue by jkabat** [antishov/StofDoctrineExtensionsBundle#5]
Latest commits are not yet tagged, will you plan to do it?

Also this fork is unusable on environments with shared folders - docker configuration paths contains wrong characters:

```bash
checkdir error:  cannot create /home/vagrant/app/vendor/composer/02108b07/antishov-StofDoctrineExtensionsBundle-9dcb4b5/.docker/php:7.1
                 Protocol error
                 unable to process antishov-StofDoctrineExtensionsBundle-9dcb4b5/.docker/php:7.1/.
```

**Comment by bruno-buiret** [comment]
Hi, I think colons aren't allowed in Windows names, I tried requiring the dev-master version and folder `./docker/php:7.1` couldn't be created.

**Comment by antishov** [comment]
Tagged [v1.4.2](https://github.com/antishov/StofDoctrineExtensionsBundle/releases/tag/v1.4.2)
Thank you
