### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by gesior** [antishov/StofDoctrineExtensionsBundle#6]
Are you planning to update package to Symfony 5.0?
Right now composer fails with:
```
    - antishov/doctrine-extensions-bundle dev-master requires symfony/framework-bundle ^4.3 -> no matching package found.
```

**Comment by antishov** [comment]
Hi, gesior.
Symfony 5 compatibility added by PR #7 and will be released in a few days.
