### ISSUE TITLE
Support for Symfony 5

### ISSUE THREAD

**Issue by christiansiewert** [antishov/StofDoctrineExtensionsBundle#8]
Hey and thank you for forking this. Can you please tag a new version for Symfony 5?

**Comment by antishov** [comment]
Hi, @siewert87.
Symfony 5 support is already in master and will be tagged in a few days. There is some work to do before.

**Comment by christiansiewert** [comment]
Thank you.

**Comment by antishov** [comment]
v1.4.1 has been released

**Comment by Sozialarchiv** [comment]
Great work! Thank you very much.
