### ISSUE TITLE
fatal: cannot create directory at '.docker/php:7.1': Invalid argument

### ISSUE THREAD

**Issue by bloushed** [antishov/StofDoctrineExtensionsBundle#9]
Since 1.4.1 (Symfony 4.4), I have this error when I update my composer, I had to use the previous version to fix this (1.4.0)

**Comment by antishov** [comment]
Hi, @leoborel 
Fix is in the master, could you check it?

**Comment by bloushed** [comment]
I tried to update my composer with the version 1.4.1, but always the same error :(

**Comment by jkabat** [comment]
@leoborel fix was not tagged yet, try to use dev-master.

**Comment by bloushed** [comment]
oops sorry I hurried up ... It's ok with dev-master !

**Comment by antishov** [comment]
Tagged [v1.4.2](https://github.com/antishov/StofDoctrineExtensionsBundle/releases/tag/v1.4.2)
Thank you
